server:
  port: 8010

spring:
  security:
      user:
          name: "root"
          password: "root"
  application:
    name: @pom.artifactId@

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

